### ISSUE TITLE
Fork build fail

### ISSUE THREAD

**Issue by NHKK** [SlightHeadache/zmk-config#2]
Hi, I recently forked your repo for choctopus44 and when I try to run the build it fails. I don't have familiarity with GitHub actions nor zmk hoping to provide failure details in order to get some assistance.

Here's the error I'm seeing:

Run west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=choctopus44 -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
  west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=choctopus44 -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
  shell: sh -e {0}
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
CMake Error at /__w/zmk-config/zmk-config/zephyr/cmake/modules/zephyr_default.cmake:18 (cmake_minimum_required):
  CMake 3.20.0 or higher is required.  You are running version 3.16.3
Call Stack (most recent call first):
  /__w/zmk-config/zmk-config/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /__w/zmk-config/zmk-config/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:15 (find_package)

**Comment by SlightHeadache** [comment]
> CMake 3.20.0 or higher is required. You are running version 3.16.3

I suspect that this might be caused by the container image used to build the firmware is too old for the current version of ZMK. I had a similar issue locally when making Choctopus44v2. I'm in the process of finalizing the Choctopus44v2 project so any problems with this repo should get fixed in the next couple of weeks.

However, if you're in a rush you could try upgrading the image version used in your fork, see: https://github.com/SlightHeadache/zmk-config/blob/master/.github/workflows/build.yml#L9

**Comment by NHKK** [comment]
Thanks I got it to work a different way. I made a new repo and make small adjustment to the key map and that seem to do the trick. Why that works no idea.
